GeoMap: examples/testWebMercator/src/main.cpp File Reference
main.cpp File Reference
#include "../../../includes/WebMercator.h"
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
Classes
struct Position
This struct is to store the valus from parsing the arguments by user.
Functions
int parseArgs (int argc, char **argv, Position &oPosition)
Parse arguments from user.
void parseGPS (Position &oPosition)
Parse GPS point to connvert the coordinate system.
int main (int argc, char **argv)
Class Documentation
Position
struct Position
This struct is to store the valus from parsing the arguments by user.
Class Members
double dLat The GPS latitude.
double dLong The GPS longitude.
int iZoom The tile map level.
Function Documentation
main()
int main (int argc, char ** argv)
References Position::dLat, Position::dLong, Position::iZoom, parseArgs(), and parseGPS().
parseArgs()
int parseArgs (int argc, char ** argv, Position & oPosition)
Parse arguments from user.
Parameters
argc The number of the arguments.
argv The list of the arguments.
Return values
0 Succeed to parse the arguments.
-1 Fail to parse the arguments.
1 Show usage.
References Position::dLat, Position::dLong, and Position::iZoom.
Referenced by main().
parseGPS()
void parseGPS (Position & oPosition)
Parse GPS point to connvert the coordinate system.
Parameters
oPosition This struct contains GPS point.
References Position::dLat, Position::dLong, Position::iZoom, lat2TileY(), and long2TileX().
Referenced by main().